# Generated by Django 3.1.5 on 2021-05-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0002_auto_20210502_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preconditions',
        ),
    ]
