# Generated by Django 3.1.5 on 2021-05-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0005_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('ENT', 'ENT'), ('DERMATOLOGY', 'DERMATOLOGY'), ('NEUROLOGY', 'NEUROLOGY'), ('DENTAL', 'DENTAL')], default='Unspecified', max_length=100),
        ),
    ]
