# Generated by Django 3.1.5 on 2021-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0008_patient_precondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='precondition',
            field=models.CharField(choices=[('NONE', 'NONE'), ('ASTHMA', 'ASTHMA'), ('DIABETES', 'DIABETES'), ('HYPERTENSION', 'HYPERTENSION')], default='Unspecified', max_length=100),
        ),
    ]
