# Generated by Django 3.1.5 on 2021-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0009_auto_20210502_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergic',
            field=models.BooleanField(default=False),
        ),
    ]
