# Generated by Django 3.1.5 on 2021-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0010_patient_allergic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
