# Generated by Django 3.1.5 on 2021-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0011_patient_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
