# Generated by Django 3.1.5 on 2021-05-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0012_patient_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
    ]
