# Generated by Django 3.1.5 on 2021-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0015_auto_20210502_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
