# Generated by Django 3.1.5 on 2021-05-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0016_auto_20210502_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='prescription',
            new_name='profile',
        ),
    ]
